rvm:
  - 2.2.3
before_script:
  - createuser -s workshops
  - createdb workshops_test
  - createdb workshops_development
  - psql -c 'grant all privileges on database workshops_test to workshops'
  - psql -c 'grant all privileges on database workshops_development to workshops'
addons:
  postgresql: '9.3'
